9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','about','About Legend of the Green Dragon','Об игре','wmza','1.1.2 Dragonprime Edition'),
('ru','about','About LoGD','Про игру','','1.1.2 Dragonprime Edition'),
('ru','about','Administrative','Администрация','','1.1.2 Dragonprime Edition'),
('ru','about','All versions, starting with the 0.9.8-prerelease code are only licensed under the Creative Commons license.','Все версии, начиная с 0.9.8-бета-версия только под лицензией Creative Commons лицензии.','wmza','1.1.2 Dragonprime Edition'),
('ru','about','Amount of gold to start a new character with','Количество золота у новичка после регистрации','wmza','1.1.2 Dragonprime Edition'),
('ru','about','Automatically delete old messages after (days)','Автоматическое удаление старых писем через (дней)','wmza','1.1.2 Dragonprime Edition'),
('ru','about','Bank settings','Настройки банка','wmza','1.1.2 Dragonprime Edition'),
('ru','about','Content Expiration','Сроки действия','','1.1.2 Dragonprime Edition'),
('ru','about','Current game time','Текущее время игры','wmza','1.1.2 Dragonprime Edition'),
('ru','about','Darkhorse Game','Игра Темная Лошадь','','1.1.2 Dragonprime Edition'),
('ru','about','Download','Загрузить','wmza','1.1.2 Dragonprime Edition'),
('ru','about','Forest','Лес','','1.1.2 Dragonprime Edition'),
('ru','about','Game Setup','Установки игры','','1.1.2 Dragonprime Edition'),
('ru','about','Game Setup Info','Настройки игры','','1.1.2 Dragonprime Edition'),
('ru','about','Game days per calendar day','Игровые дни за один календарный день','','1.1.2 Dragonprime Edition'),
('ru','about','Gardens','Сады','','1.1.2 Dragonprime Edition'),
('ru','about','General','Основные','','1.1.2 Dragonprime Edition'),
('ru','about','Inn','Трактир','','1.1.2 Dragonprime Edition'),
('ru','about','Mail Settings','Почта','','1.1.2 Dragonprime Edition'),
('ru','about','Map','Карта','wmza','1.1.2 Dragonprime Edition'),
('ru','about','Maps','Карты','','1.1.2 Dragonprime Edition'),
('ru','about','Module Author','Автор модуля','','1.1.2 Dragonprime Edition'),
('ru','about','Module Name','Название модуля','','1.1.2 Dragonprime Edition'),
('ru','about','New Days','Новые дни','','1.1.2 Dragonprime Edition'),
('ru','about','Races','Расы','','1.1.2 Dragonprime Edition'),
('ru','about','Testing','Тестирование','','1.1.2 Dragonprime Edition'),
('ru','about','Translations','Переводы','','1.1.2 Dragonprime Edition'),
('ru','about','Version','Версия','','1.1.2 Dragonprime Edition'),
('ru','about','Village','Город','','1.1.2 Dragonprime Edition'),
('ru','about','`cLoGD version ','`cLoGD версия ','wmza','1.1.2 Dragonprime Edition');