9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','bio','Character Biography: %s','Биография персонажа: %s','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','Edit User','Редактировать игрока','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','Female','Женский','wmza','1.1.2 Dragonprime Edition'),
('ru','bio','Male','Мужской','wmza','1.1.2 Dragonprime Edition'),
('ru','bio','Moderation','Модерация','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','Refresh','Обновить','','1.1.2 Dragonprime Edition'),
('ru','bio','Return to Comment Moderation','Вернуться в Модерацию Комментариев','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','Superuser','Администрация','','1.1.2 Dragonprime Edition'),
('ru','bio','Unspecified','Не выбрано','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','Write Mail','Написать письмо','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','`#Online`0','`#Онлайн`0','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','`^Biography for %s`^.','`^Биография %s`^.','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','`^Creature: `@%s`0`n','`^Животное: `@%s`0`n','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','`^Dragon Kills: `@%s`n','`^Убил Драконов: `@%s`n','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','`^Gender: `@%s`n','`^Пол: `@%s`n','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','`^Level: `@%s`n','`^Уровень: `@%s`n','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','`^Race: `@%s`n','`^Раса: `@%s`n','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','`^Specialty: `@%s`n','`^Специальность: `@%s`n','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','`^Status: %s`n','`^Статус: %s`n','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','`^Title: `@%s`n','`^Титул: `@%s`n','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','`iNone`i','`iНикого`i','wmza','1.1.2 Dragonprime Edition '),
('ru','bio','`n`^Recent accomplishments (and defeats) of %s`^','`n`^Последние достижения (и поражения) у %s`^','wmza','1.1.2 Dragonprime Edition ');