9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','claneditor','(%s member)','(%s игрок)','','1.1.2 Dragonprime Edition'),
('ru','claneditor','(%s members)','(%s игроков)','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Apply','Создать','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Clan Listing','Список кланов','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Clan Name: ','Название клана: ','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Clan Options','Кланы','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Clans','Кланы','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Congratulations, you\'ve created a new clan named %s!','Поздравляю, вы создали новый клан под названием - \"%s\"!','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Dragon Kills','Убито Драконов','','1.1.2 Dragonprime Edition'),
('ru','claneditor','First, you have to decide on a full name for your clan.','Во-первых, вы должны решить, на полное имя для вашего клана.
','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Join Date','Основан','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Last On','Последний вход','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Level','Уровень','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Name','Имя','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Operations','Операции','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Rank','Ранг','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Save','Сохранить','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Search','Поиск','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Second, you have to decide on an abbreviation for your clan.','Во-вторых, вы должны принять решение о аббревиатуры для вашего клана.
','','1.1.2 Dragonprime Edition'),
('ru','claneditor','She tells you that there are three requirements to starting a clan.','Она говорит вам, что есть три требования к начиная клана.','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Updating MoTD`n','Обновление новостей`n','','1.1.2 Dragonprime Edition'),
('ru','claneditor','Updating description`n','Обновление описания`n','','1.1.2 Dragonprime Edition'),
('ru','claneditor','`&`bCurrent MoTD:`b `#by %s`2`n','`&`bНовости клана:`b `#написал %s`2`n','','1.1.2 Dragonprime Edition'),
('ru','claneditor','`&`bMoTD:`b `7(4096 chars)`n','`&`bНовости:`b `7(4096 символов)`n','','1.1.2 Dragonprime Edition'),
('ru','claneditor','`nShort Name: ','`nАббревиатура: ','','1.1.2 Dragonprime Edition'),
('ru','claneditor','`n`&`bDescription:`b `7(4096 chars)`n','`n`&`bОписание:`b `7(4096 символов)`n','','1.1.2 Dragonprime Edition'),
('ru','claneditor','`n`n\"`5If you\'re ok with these three requirements, please fill out the following form,`7\" she says, handing you a sheet of paper.','`n`n\"`5Если вы соглашаетесь с этими требованиями, пожалуйста, заполните приведенную ниже форму`7\" говорит она, вручая вам листок бумаги.','','1.1.2 Dragonprime Edition'),
('ru','claneditor','`n`n`^This clan has a total of `$%s`^ dragon kills.','`n`n`^Этот клан убил `$%s`^ драконов.','','1.1.2 Dragonprime Edition');