9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','clans','!?Yes','Да','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','%s`7 looks over your form but informs you that your clan name must consist only of letters, spaces, apostrophes, or dashes.  Also, your short name can consist only of letters. She hands you a blank form.','%s`7 смотрит на вашу форму, но сообщает, что ваш клан имя должно состоять только из букв, пробелов, апостроф или тире. Кроме того, ваше краткое имя может состоять только из букв. Она вручает вам бланк.','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','(%s member)','(%s игрок)','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','(%s members)','(%s игроков)','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Apply','Создать','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Apply for Membership to a Clan','Подать заявку на вступление в клан','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Apply for a New Clan','Создать новый клан','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Are you sure you want to withdraw from your clan?','Вы уверены, что хотите выйти из вашего клана?','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','C?List Clans','Список кланов','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Clan Hall','Холл Клана','','1.1.2 Dragonprime Edition'),
('ru','clans','Clan Hall for %s','Холл Клана для %s','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Clan Halls','Зал Кланов','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Clan Listing','Список кланов','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Clan Membership for %s &lt;%s&gt;','Участники Клана - %s &lt;%s&gt;','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Clan Name: ','Название клана: ','wmza','1.1.2 Dragonprime Edition'),
('ru','clans','Clan Options','Кланы','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Congratulations, you\'ve created a new clan named %s!','Поздравляю, вы создали новый клан под названием - \"%s\"!','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Dragon Kills','Убито Драконов','','1.1.2 Dragonprime Edition'),
('ru','clans','Edit Clan Info','Изменить информацию клана','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Enter your clan hall','Войти в свой клан','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','First, you have to decide on a full name for your clan.','Во-первых, вы должны решить, на полное имя для вашего клана.
','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Having pressed the secret levers and turned the secret knobs on the lock of the door to your clan\'s hall, you gain entrance and chat with your clan mates.`n`n','Нажав на тайные рычаги и повернулся секрет ручки на замок дверь в зал вашего клана, вы получаете вход и общаться со своими помощниками клана.`n`n','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Join Date','Основан','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Last On','Последний вход','','1.1.2 Dragonprime Edition'),
('ru','clans','Level','Уровень','','1.1.2 Dragonprime Edition'),
('ru','clans','M?View Membership','Смотреть игроков','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Name','Имя','','1.1.2 Dragonprime Edition'),
('ru','clans','No','Нет','','1.1.2 Dragonprime Edition'),
('ru','clans','Online Members','Игроки онлайн','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Operations','Операции','','1.1.2 Dragonprime Edition'),
('ru','clans','Rank','Ранг','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Return to the Lobby','Вернуться в Холл','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Return to your Clan Rooms','Вернуться в ваш клан','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Return to your clan hall','Вернуться назад','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Save','Сохранить','','1.1.2 Dragonprime Edition'),
('ru','clans','Second, you have to decide on an abbreviation for your clan.','Во-вторых, вы должны принять решение о аббревиатуры для вашего клана.
','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','She stares at you blankly for a few moments, then says, \"`5Sorry pal, no one has had enough gumption to start up a clan yet.  Maybe that should be you, eh?`7\"','Она на тебя тупо смотрит несколько минут, и говорит, \"`5Извени приятель, никто еще не сообразил как создать клан.  Может быть, это вы?`7\"','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','She tells you that there are three requirements to starting a clan.','Она говорит вам, что есть три требования к начиная клана.','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','The fees are as follows:`nGold: `^%s`7`nGems: `%%s`7','Стоимость создания:`nЗолота: `^%s`7`nКристалов: `%%s`7','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Third you have to decide on whether or not you\'re willing to give up the fees that are required to start the clan.','Третье вы должны решить, от наличия или отсутствия вы готовы отказаться от сборов, которые необходимы, чтобы начать клан.','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','This fee is used to tailor the locks on your clan door to you and your members.`n','Эта плата используется для портного замки на двери вашего клана к Вам и членам Вашей.`n','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Update Clan Description / MoTD','Обновления Клана Описания/Новости','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Update MoTD / Clan Desc','Новости/Описание клана','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Updating MoTD`n','Обновление новостей`n','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Updating description`n','Обновление описания`n','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Village','Город','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Withdraw From Your Clan','Выйти из клана','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Withdraw?','Покинуть?','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','You are not a member of any clan.','Вы не состоите неводном из кланов.','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Your Clan\'s Waiting Area','Зал лжидания Кланов','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','Your clan has been blocked from posting a description.`n','Ваш клан был заблокирован за размещения описания.`n','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`!Applicant`0','`!Заявитель`0','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`#Member`0','`#Игрок`0','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`$Founder','`$Основатель','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`&Leader`0','`&Лидер`0','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`&`bCurrent MoTD:`b `#by %s`2`n','`&`bНовости клана:`b `#написал %s`2`n','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`&`bMoTD:`b `7(4096 chars)`n','`&`bНовости:`b `7(4096 символов)`n','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`7You approach %s`7 and inquire about starting a new clan.','`7Вы подходите к %s`7 и узнаете требования для создания нового клана.','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`7You ask %s`7 for a clan membership application form.','`7Вы спрашиваете у %s`7 бланк заявки для вступления в клан.','wmza','1.1.2 Dragonprime Edition'),
('ru','clans','`^Officer`0','`^Офицер`0','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`b`cNew Clan Application Form`c`b','`b`cФорма Регистрации Клана`c`b','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`b`c`&Clan Halls`c`b','`b`c`&Зал Кланов`c`b','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`nShort Name: ','`nАббревиатура: ','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`n`&`bDescription:`b `7(4096 chars)`n','`n`&`bОписание:`b `7(4096 символов)`n','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`n`n\"`5If you\'re ok with these three requirements, please fill out the following form,`7\" she says, handing you a sheet of paper.','`n`n\"`5Если вы соглашаетесь с этими требованиями, пожалуйста, заполните приведенную ниже форму`7\" говорит она, вручая вам листок бумаги.','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`n`n\"`5Since you do not have enough gems with you, I cannot allow you to apply for a clan,`7\" she says.','`n`n\"`5Так как вам не хватает драгоценных камней, я не могу разрешить вам создать новый клан`7\" she says.','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`n`n\"`5Since you do not have enough gold with you, I cannot allow you to apply for a clan,`7\" she says.','`n`n\"`5Так-как у вас с собою нету такой суммы, Я не разрешаю Вам создать свой клан`7\" говорит она.','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`n`n`&`bCurrent Description:`b `#by %s`2`n','`n`n`&`bОписание Клана:`b `#написал %s`2`n','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`n`n`^This clan has a total of `$%s`^ dragon kills.','`n`n`^Этот клан убил `$%s`^ драконов.','wmza','1.1.2 Dragonprime Edition '),
('ru','clans','`n`n`bMembership Details:`b`n','`n`n`bСостав клана:`b`n','wmza','1.1.2 Dragonprime Edition'),
('ru','clans','says','говорит','','1.1.2 Dragonprime Edition');