9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','commentary',' characters left.',' знаков.','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','%s','%s','wmza','1.1.2 Dragonprime Edition'),
('ru','commentary','%s Square','%s Площадь','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','%s Village','%s Деревня','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','&lt; Previous','&lt; Предыдущая','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','&lt;&lt; First Unseen','&lt;&lt; Первая страница','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','Add','Добавить','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','City of %s','Город %s','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','Clan Hall Waiting Area','Клан Холл зал ожидания','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','Del','Удалить','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','Gardens','Сады','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','Grassy Field','Поляна','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','Grotto','Грот','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','Hunter\'s Lodge','Дом охотников','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','Land of the Shades','Земля Теней','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','Last Page &gt;&gt;','Последняя страница &gt;&gt;','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','MotD','Новости','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','Next &gt;','Следующая &gt;','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','Refresh','Обновить','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','Veterans Club','Клуб ветеранов','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','You have ','Вы можете использовать еще','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','`n`@Engage in idle conversation with other gods:`n','`n`@Участровать в простом разговоре с другими богами:`n','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','`n`@Interject your own commentary?`n','`n`@Оставить ваш собственный комментарий?`n','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','`n`@Speak`n','`n`@Говорить`n','wmza','1.1.2 Dragonprime Edition'),
('ru','commentary','brags','ворчит','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','converses','напевает','wmza','1.1.2 Dragonprime Edition '),
('ru','commentary','says','говорит','wmza','1.1.2 Dragonprime Edition ');