9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','common','Companions','Спутники','wmza','1.1.2 Dragonprime Edition '),
('ru','common','Equipment Info','Экипировка','wmza','1.1.2 Dragonprime Edition '),
('ru','common','Extra Info','Дополнительнаяи информация','wmza','1.1.2 Dragonprime Edition '),
('ru','common','Missing function','Функция отсутствует','wmza','1.1.2 Dragonprime Edition '),
('ru','common','MoTD','Новости','wmza','1.1.2 Dragonprime Edition '),
('ru','common','Not specified','Не указано','wmza','1.1.2 Dragonprime Edition'),
('ru','common','Personal Info','Персональная информация','wmza','1.1.2 Dragonprime Edition '),
('ru','common','Petition for Help','Пожаловаться','wmza','1.1.2 Dragonprime Edition '),
('ru','common','View PHP Source','Смотреть PHP исходник','wmza','1.1.2 Dragonprime Edition '),
('ru','common','Vital Info','О вашей жизни','wmza','1.1.2 Dragonprime Edition'),
('ru','common','Ye Olde Mail: %s new, %s old','Ваша почта: %s новых, %s старых','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Armor`0','`&Броня`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Attack`0','`&Атака`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Creature`0','`&Создание`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Defense`0','`&Защита`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Experience`0','`&Опыт`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Favor`0','`&Благосклонность`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Free Travel`0','`&Свободные путешествия`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Gems`0','`&Кристалы`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Gold`0','`&Золото`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Hitpoints`0','`&Жизнь`0','wmza','1.1.2 Dragonprime Edition'),
('ru','common','`&Home City`0','`&Родной город`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Level`0','`&Уровень`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Name`0','`&Имя`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Psyche`0','`&Психика`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Race`0','`&Раса`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Soulpoints`0','`&Очки душ`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Spirit`0','`&Духа`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Spirits`0','`&Настроение`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Torments`0','`&Муки`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Turns`0','`&Поединки`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&Weapon`0','`&Оружие`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`&`4Skeleton Warrior`0','`&`4Скелет воин`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`0Buffs','`0Особые эффекты','wmza','1.1.2 Dragonprime Edition'),
('ru','common','`0`bPetitions:`b','`0`bЖалобы:`b','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`0`bUser Editor`b','`0`bРедактор игроков`b','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`^None`0','`^Пусто`0','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`bDEAD`b','`bМЕРТВЫЙ`b','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`bHigh`b','`bВысокое`b','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`bLow`b','`bНизкое`b','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`bNormal`b','`bНормально`b','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`bOnline Characters (%s players):`b`n','`bПерсонажи онлайн (%s игроков):`b`n','wmza','1.1.2 Dragonprime Edition'),
('ru','common','`bVery Low`b','`bОчень низкое`b','wmza','1.1.2 Dragonprime Edition '),
('ru','common','`iNone`i','`iПусто`i','wmza','1.1.2 Dragonprime Edition'),
('ru','common','`nYour session has expired!`n','`nВы были долго неактивны в игре!`n','wmza','1.1.2 Dragonprime Edition'),
('ru','common','`n`3Module `#%s`3 is not active, but was attempted to be injected.`n','`n`3Модуль `#%s` не активен, но была попытка его включения.`n','wmza','1.1.2 Dragonprime Edition');