9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','companions','Activate','Включить','','1.1.2 Dragonprime Edition'),
('ru','companions','Add a companion','Добавить компаньона','wmza','1.1.2 Dragonprime Edition'),
('ru','companions','Allow in PvP:','Разрешить в ПвП','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Allow in shades:','Разрешить в тени:','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Allow in train:','Разрешить в поезде:','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Attack / Bonus per level:','Атака / Бонус за уровень','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Category: %s','Категория: %s','','1.1.2 Dragonprime Edition'),
('ru','companions','Companion Availability:','Где находится:','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Companion Category:','Категория спутника:','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Companion Cost (DKs):','Стоимость (ДК):','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Companion Cost (Gems):','Стоимость (Кристалов)','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Companion Cost (Gold):','Стоимость (Золото)','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Companion Description:','Описание спутника:','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Companion Editor','Редактор спутников','','1.1.2 Dragonprime Edition'),
('ru','companions','Companion Editor:`n','Редактор спутников:`n','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Companion Name:','Имя спутника:','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Companion cannot be healed:','Не может быть исцелен:','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Companion cannot die:','Не может умереть:','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Companion join text:','Текст присоедин. спутника','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Cost','Стоимость','','1.1.2 Dragonprime Edition'),
('ru','companions','Deactivate','Отключить','','1.1.2 Dragonprime Edition'),
('ru','companions','Defender?:','Защитник?:','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Defense / Bonus per level:','Защита / Бонус за уровень','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Del','Удалить','','1.1.2 Dragonprime Edition'),
('ru','companions','Edit','Изменить','','1.1.2 Dragonprime Edition'),
('ru','companions','Everywhere','Везде','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Fighter?:','Боец?:','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Healer level:','Уровень целителя?:','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Magician?:','Маг?:','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Maxhitpoints / Bonus per level:','Макс Жизни / Ьонус за уровень','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Name','Имя','','1.1.2 Dragonprime Edition'),
('ru','companions','Ops','Ops','','1.1.2 Dragonprime Edition'),
('ru','companions','Save','Сохранить','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','Take','Дать','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','The Village of %s','В деревне %s','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','`%%s gems`0, `^%s gold`0','`%%s кристалы`0, `^%s золота`0','','1.1.2 Dragonprime Edition'),
('ru','companions','`^Companion `$not`^ saved: `$%s`0`n`n','`^Компаньен `$не`^ сохранен: `$%s`0`n`n','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','`iThis value determines the maximum amount of HP healed per round`i','`iЭто значение определяет максимальное количество HP исцелил за раунд`i','wmza','1.1.2 Dragonprime Edition '),
('ru','companions','`iThis value determines the maximum amount of damage caused per round`i','`iЭто значение определяет максимальный размер ущерба, причиненного за раунд`i','wmza','1.1.2 Dragonprime Edition ');