9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','configuration','%s Modules','%s Модули','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Account Creation','Создание аккаунтов','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Activate','Включить','','1.1.2 Dragonprime Edition'),
('ru','configuration','Allow creation of new characters','Разрешить создание новых персонажей','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Allow fighting multiple rounds automatically','Разрешить несколько раундов автоматической борьбы','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Allow fighting until fight is over','Разрешить драться пока драка не закончена','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Always','Всегда','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Amount of gold to start a new character with','Количество золота у новичка после регистрации','','1.1.2 Dragonprime Edition'),
('ru','configuration','Are we currently collecting untranslated texts?','Неужели мы в настоящее время сбор нетранслируемым текстах?','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Automatically delete old messages after (days)','Автоматическое удаление старых писем через (дней)','','1.1.2 Dragonprime Edition'),
('ru','configuration','Bank','Банк','','1.1.2 Dragonprime Edition'),
('ru','configuration','Bank Settings','Настройки Банка','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Beta Setup','Бета настройки','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Cache the translations (datacache must be turned on)?','Кэшируйте переводы (DataCache должна быть включена)?','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Can players gain multiple levels (challenge multiple masters) per game day?','Игроки могут получить несколько уровней (вызов несколько мастеров) в игровой день?','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Chance for Something Special in any village','Шанс на что-то особенное в деревне','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Chance for Something Special in the Forest','Шанс на что-то особенное в лесу','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Chance for Something Special in the Gardens','Шанс на что-то особенное в садах','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Chance for Something Special in the Graveyard','Шанс на что-то особенное на кладбище','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Chance for Something Special in the Inn','Шанс на что-то особенное в Inn','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Cities','Города','','1.1.2 Dragonprime Edition'),
('ru','configuration','Clans','Кланы','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Collect untranslated texts if you have fewer player than this logged in. (0 never collects)','Сбор нетранслируемым тексты, если у вас меньше игроков, чем это прошли идентификацию (0 никогда не собирает)','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Commentary/Chat','Комментария/Чат','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Companions/Mercenaries','Спутники/Наемники','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Content Expiration','Сроки действия','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Current game time','Текущее время игры','','1.1.2 Dragonprime Edition'),
('ru','configuration','Deactivate','Отключить','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Default Language','Язык по умолчанию','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Display news if somebody fought his master?','Показать новость, если кто-то победил своего хозяина?','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Does Merick have feed onhand for creatures','Есть ли у Меррика корм для животных','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Enable the use of the translation engine','Включите использование средство перевода','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','English','English','','1.1.2 Dragonprime Edition'),
('ru','configuration','Forest','Лес','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Game Settings','Настройки игры','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Game Setup','Установки игры','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Game day Setup','Игровой день','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Game days per calendar day','Игровые дни за один календарный день','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','General','Основные','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','General Combat','Главные битвы','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','High Load Optimization','Высокая оптимизация нагрузки','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','How many items should be shown on the motdlist','Сколько элементов должно быть показано на motdlist','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','If you do not know what a Cronjob is... leave it turned off. If you want to know more... check out: <a href=\'http://wiki.dragonprime.net/index.php?title=Cronjob\'>http://wiki.dragonprime.net/index.php?title=Cronjob</a>','Если вы не знаете, что это ... Cronjob оставьте его отключенным. Если вы хотите узнать больше ... проверить:: <a href=\'http://wiki.dragonprime.net/index.php?title=Cronjob\'>http://wiki.dragonprime.net/index.php?title=Cronjob</a>','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Inn','Трактир','','1.1.2 Dragonprime Edition'),
('ru','configuration','It is strongly recommended to leave this feature turned on.','Настоятельно рекомендуется оставить эту функцию включены.','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Login Banner (under login prompt: 255 chars)','Login Banner (строка под логином: 255 симв.)','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Mail Settings','Почта','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Main Page Display','Главная страница','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Map','Карта','','1.1.2 Dragonprime Edition'),
('ru','configuration','Maps','Карты','','1.1.2 Dragonprime Edition'),
('ru','configuration','Masters hunt down truant students','Мастера следят за прогулами студентов','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Max # of players online (0 for unlimited)','Макс # колличество игроков онлайн (0 неограниченно)','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Maximum number of items to be shown in the warrior list','Максимальное количество элементов, которые будут показаны в списке воина','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Miscellaneous Settings','Дополнительные настройки','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Modify (+ or -) the number of turns deducted after a resurrection as an absolute (number) or relative (number followed by %)','Изменение (+ или -) числа витков расшифрованной после воскресения как абсолютные (число) или относительными (число последующей%)','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Module Category - `^%s`0','Категория модуля - `^%s`0','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Module Manager','Менеджер модулей','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Multiple Enemies','Несколько врагов','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Never','Никогда','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','New Days','Новые дни','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Only when not allowed to flee','Только тогда, когда нельзя убежать','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Paypal','Paypal','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Permanently collect untranslated texts (overrides the next settings!)','Постоянно собираем нетранслируемым текстов (перекрывает следующие настройки!)','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Place names and People names','Имена персонажей и городов','wmza','1.1.2 Dragonprime Edition'),
('ru','configuration','Races','Расы','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Random events','Случайные события','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Referral Settings','Настройки реффералов','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Setting %s to %s`n','Настройка %s в %s`n','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Should submitted petitions be emailed to Admin Email address?','Отправлять жалобы на емаил администратору?','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Stables','Конюшня','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Standard settings','Стандартные настройки','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','The Barkeeper may help you to switch your specialty?','Бармен может изменить вам специальность?','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','The directory is necessary! Do not forget to set the correct one in cron.php in your main game folder!!! ONLY experienced admins should use cron jobbing here','Каталог нужно! Не забудьте установить правильный в cron.php в вашей основной папке игры! Только опытные администраторы должны использовать Cron ажиотажа здесь','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','This has been moved to the dbconnect.php','Она перенесена в dbconnect.php','wmza','1.1.2 Dragonprime Edition'),
('ru','configuration','This module is currently active: ','Этот модуль на данный момент является Активным: ','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','This module is currently deactivated: ','Этот модуль сейчас отключен:','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Training','Тренировка','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Translation Setup','Настройки перевода','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Translations','Переводы','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Village','Город','','1.1.2 Dragonprime Edition'),
('ru','configuration','Which charset should be used for htmlentities?','Какая кодировка должна использоваться для htmlentities?','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','`^Module %s settings saved.`0`n','`^Модуль %s настройки сохраннены.`0`n','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','`^Settings saved.`0','`^Настройки сохраннены.`0','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','`bAlso make sure you setup a cronjob on your machine using confixx/plesk/cpanel or any other admin panel pointing to the cron.php file in your main folder`b','`bТакже убедитесь, что у вас настроено Cronjob на вашей машине с помощью Confixx / Plesk / Cpanel или любой другой админ-панели указывает на cron.php файл в корневой папке`b','wmza','1.1.2 Dragonprime Edition '),
('ru','configuration','Русский','Русский','wmza','1.1.2 Dragonprime Edition ');