9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','create','Click here to log in','Нажмите сюда чтобы войти','wmza','1.1.2 Dragonprime Edition'),
('ru','create','Create A Character','Создать Игрока','wmza','1.1.2 Dragonprime Edition'),
('ru','create','Create your character','Создать своего игрока','wmza','1.1.2 Dragonprime Edition'),
('ru','create','Email me my password','Отправить пароль на мою почту','wmza','1.1.2 Dragonprime Edition'),
('ru','create','Enter a password: ','Введите пароль:','wmza','1.1.2 Dragonprime Edition'),
('ru','create','Enter your character\'s name: ','Введите имя вашего игрока:','wmza','1.1.2 Dragonprime Edition'),
('ru','create','Enter your email address: ','Введите ваш Email адрес:','wmza','1.1.2 Dragonprime Edition'),
('ru','create','How will you be known to this world? ','как вас будут называть в этом мире? ','wmza','1.1.2 Dragonprime Edition'),
('ru','create','Login','Логин','','1.1.2 Dragonprime Edition'),
('ru','create','Re-enter it for confirmation: ','Введите еще раз для подтверждения: ','wmza','1.1.2 Dragonprime Edition'),
('ru','create','Your account was created, your login name is `^%s`0.`n`n','Ваш аккаунт был создан, ваш логин `^%s`0.`n`n','wmza','1.1.2 Dragonprime Edition'),
('ru','create','`$(required)`0','`$(обязательно)`0','wmza','1.1.2 Dragonprime Edition'),
('ru','create','`$(required, an email will be sent to this address to verify it before you can log in)`0','`$(обязательно, будет отправлено на этот адрес, чтобы проверить его, прежде чем вы можете войти)`0','wmza','1.1.2 Dragonprime Edition'),
('ru','create','`&`c`bCreate a Character`b`c`0','`&`c`bСоздание Персонажа`b`c`0','wmza','1.1.2 Dragonprime Edition'),
('ru','create','`^(optional -- however, if you choose not to enter one, there will be no way that you can reset your password if you forget it!)`0','`^(необязательно - однако, если вы не хотите указывать почту, не будет никакого способа, которым вы можете восстановить ваш пароль, если вы его забудете)`0','wmza','1.1.2 Dragonprime Edition'),
('ru','create','`^Characters that have never been logged into will be deleted after %s day(s) of no activity.`n`0','`^Персонажи которые неактивны %s дней, будут удаляться из игры.`n`0','wmza','1.1.2 Dragonprime Edition'),
('ru','create','`^Characters that have never reached level 2 will be deleted after %s days of no activity.`n`0','`^Персонажи которые никогда не достигали 2 уровня, будут удаляться через %s дней, если не будут активны в игре.`n`0','wmza','1.1.2 Dragonprime Edition'),
('ru','create','`^Characters that have reached level 2 at least once will be deleted after %s days of no activity.`n`0','`^Персонажи которые достигли 2 уровень всего лишь один раз, будут удаляться через %s дней, если не будут активны в игре.`n`0','wmza','1.1.2 Dragonprime Edition'),
('ru','create','`bForgotten Passwords:`b`n`n','`bЗабыли пароль:`b`n`n','wmza','1.1.2 Dragonprime Edition'),
('ru','create','`nAnd are you a %s Female or a %s Male?`n','`nВы %s Женщина или %s Мущина?`n','wmza','1.1.2 Dragonprime Edition');