9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','creatures','Add','Добавить','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Add Another Creature','Добавить другого существа','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Add a creature','Добавить существо','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Are you sure you wish to delete this creature?','Вы уверены что хотите удалить это существо?','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Author','Автор','','1.1.2 Dragonprime Edition'),
('ru','creatures','Creature Editor','Редактор существ','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Creature Name','Название существа','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Creature Properties','Свойства существа','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Creature id','Id существа','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Creature is in forest?','Существо в лесу?','wmza','1.1.2 Dragonprime Edition'),
('ru','creatures','Creature is in graveyard?','Существо на кладбище?','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Del','Удалить','','1.1.2 Dragonprime Edition'),
('ru','creatures','Die','Умер','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Edit','Изменить','','1.1.2 Dragonprime Edition'),
('ru','creatures','ID','ID','','1.1.2 Dragonprime Edition'),
('ru','creatures','Level','Уровень','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Level %s: (%s creatures)','Уровень %s: (%s существ)','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Levels','Уровни','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Name','Имя','','1.1.2 Dragonprime Edition'),
('ru','creatures','Ops','Ops','wmza','1.1.2 Dragonprime Edition'),
('ru','creatures','Return to the creature editor','Вернуться в редактор существ','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Search','Поиск','','1.1.2 Dragonprime Edition'),
('ru','creatures','Search by field: ','Поле поиска: ','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Weapon','Оружие','wmza','1.1.2 Dragonprime Edition '),
('ru','creatures','Win','Поб','wmza','1.1.2 Dragonprime Edition ');