9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','home',' Your session has timed out, you must log in again.`n',' Ваш сеанс закончился, Вы должны снова войти в систему`n','wmza','1.1.2 Dragonprime Edition'),
('ru','home','<u>P</u>assword','<u>П</u>ароль','wmza','1.1.2 Dragonprime Edition'),
('ru','home','<u>U</u>sername','<u>Л</u>огин','wmza','1.1.2 Dragonprime Edition'),
('ru','home','About LoGD','Про игру','wmza','1.1.2 Dragonprime Edition'),
('ru','home','Choose','Выбрать','','1.1.2 Dragonprime Edition'),
('ru','home','Choose a different display skin:','Выбрать другую тему оформления игры:','wmza','1.1.2 Dragonprime Edition'),
('ru','home','Create a character','Создать персонажа','wmza','1.1.2 Dragonprime Edition'),
('ru','home','Daily News','Новости','wmza','1.1.2 Dragonprime Edition'),
('ru','home','Enter your name and password to enter the realm.`n','Введите Ваш логин и пароль для входа в игру.`n','wmza','1.1.2 Dragonprime Edition'),
('ru','home','Forgotten Password','Напомнить пороль','wmza','1.1.2 Dragonprime Edition'),
('ru','home','Game Functions','Функции игры','wmza','1.1.2 Dragonprime Edition'),
('ru','home','Game Setup Info','Настройки игры','wmza','1.1.2 Dragonprime Edition'),
('ru','home','Legend of the Green Dragon','Легенда о Зеленом Драконе','wmza','1.1.2 Dragonprime Edition'),
('ru','home','List Warriors','Список воинов','wmza','1.1.2 Dragonprime Edition'),
('ru','home','Log in','ВОЙТИ','wmza','1.1.2 Dragonprime Edition'),
('ru','home','New to LoGD?','Новичок в игре?','wmza','1.1.2 Dragonprime Edition'),
('ru','home','Other Info','Другая информация','wmza','1.1.2 Dragonprime Edition'),
('ru','home','`@Next new game day in: `$%s (real time)`0`n`n','`@Следующий новый день через: `$%s (реальное время)`0`n`n','wmza','1.1.2 Dragonprime Edition'),
('ru','home','`@The current time in %s is `%%s`@.`0`n','`@Сейчас вемя в %s - `%%s`@.`0`n','wmza','1.1.2 Dragonprime Edition'),
('ru','home','`QThe newest resident of the realm is: `&%s`0`n`n','`QНовый житель в Королевстве: `&%s`0`n`n','wmza','1.1.2 Dragonprime Edition'),
('ru','home','`cWelcome to Fear Mythos MMO (Working Name), a browser based role playing game, run by the DragonPrime Legend of the Green Dragon engine, based on Seth Able\'s Legend of the Red Dragon.`n','`cДобро пожаловать в MMO Mythos Страх (рабочее название), на основе браузера ролевая игра, в ведении Dragonprime Легенда о Зеленом двигателя Дракона, основанный на Сета Способный Легенда Красного Дракона.`n','wmza','1.1.2 Dragonprime Edition'),
('ru','home','`c`2Game server running version: `@%s`0`c','`c`2Версия игры: `@%s`0`c','wmza','1.1.2 Dragonprime Edition');