9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','list',' (%s warriors)',' (%s воинов)','wmza','1.1.2 Dragonprime Edition'),
('ru','list',' ?Page %s (%s-%s)',' ?Страница %s (%s-%s)','wmza','1.1.2 Dragonprime Edition'),
('ru','list',' ?`b`#Page %s`0 (%s-%s)`b',' ?`b`#Страница %s`0 (%s-%s)`b','wmza','1.1.2 Dragonprime Edition'),
('ru','list','Alive','Живой','wmza','1.1.2 Dragonprime Edition'),
('ru','list','Clan Hall','Холл Клана','wmza','1.1.2 Dragonprime Edition'),
('ru','list','Clan Members Online','Участники Клана Онлайн','wmza','1.1.2 Dragonprime Edition'),
('ru','list','Currently Online','Сейчас Онлайн','wmza','1.1.2 Dragonprime Edition'),
('ru','list','Last On','Последний вход','','1.1.2 Dragonprime Edition'),
('ru','list','Level','Уровень','wmza','1.1.2 Dragonprime Edition'),
('ru','list','List Warriors','Список воинов','wmza','1.1.2 Dragonprime Edition'),
('ru','list','Location','Локация','','1.1.2 Dragonprime Edition'),
('ru','list','Login Screen','Страница Входа','wmza','1.1.2 Dragonprime Edition'),
('ru','list','Name','Имя','wmza','1.1.2 Dragonprime Edition'),
('ru','list','Online Clan Members','Онлайн соклановцы','wmza','1.1.2 Dragonprime Edition '),
('ru','list','Pages','Страницы','wmza','1.1.2 Dragonprime Edition'),
('ru','list','Race','Раса','wmza','1.1.2 Dragonprime Edition'),
('ru','list','Search','Поиск','','1.1.2 Dragonprime Edition'),
('ru','list','Search by name: ','Искать по имени:','wmza','1.1.2 Dragonprime Edition'),
('ru','list','Sex','Пол','wmza','1.1.2 Dragonprime Edition'),
('ru','list','Warriors Currently Online','Воины онлайн','wmza','1.1.2 Dragonprime Edition '),
('ru','list','Warriors of the realm','Воины в игре','wmza','1.1.2 Dragonprime Edition'),
('ru','list','Write Mail','Написать письмо','','1.1.2 Dragonprime Edition'),
('ru','list','`!Male`0','`!Мужской`0','wmza','1.1.2 Dragonprime Edition '),
('ru','list','`#(Online)','`#(Онлайн)','wmza','1.1.2 Dragonprime Edition'),
('ru','list','`1Yes`0','`1Да`0','wmza','1.1.2 Dragonprime Edition'),
('ru','list','`4No`0','`4Нет`0','wmza','1.1.2 Dragonprime Edition'),
('ru','list','`6Unconscious`0','`6Бессознания`0','wmza','1.1.2 Dragonprime Edition');