9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','masters','Add master','Добавить мастера','wmza','1.1.2 Dragonprime Edition'),
('ru','masters','Are you sure you wish to delete this master.','Вы уверены что хотите удалить этого мастера?','wmza','1.1.2 Dragonprime Edition '),
('ru','masters','Functions','Функции','','1.1.2 Dragonprime Edition'),
('ru','masters','Level','Уровень','','1.1.2 Dragonprime Edition'),
('ru','masters','Lose to Master','Проигрыш Мастеру','wmza','1.1.2 Dragonprime Edition '),
('ru','masters','Masters Editor','Редактор мастеров','wmza','1.1.2 Dragonprime Edition'),
('ru','masters','Name','Имя','wmza','1.1.2 Dragonprime Edition'),
('ru','masters','Ops','Ops','wmza','1.1.2 Dragonprime Edition'),
('ru','masters','Refresh list','Обновить список','wmza','1.1.2 Dragonprime Edition '),
('ru','masters','Return to Masters Editor','Вернуться в Редактор Мастеров','wmza','1.1.2 Dragonprime Edition '),
('ru','masters','Submit','Отправить','wmza','1.1.2 Dragonprime Edition '),
('ru','masters','Weapon','Оружие','','1.1.2 Dragonprime Edition'),
('ru','masters','Win against Master','Победа над Мастером','wmza','1.1.2 Dragonprime Edition '),
('ru','masters','`^Master\'s level:`n','`^Уровень Мастера:`n','wmza','1.1.2 Dragonprime Edition '),
('ru','masters','`^Master\'s name:`n','`^Имя мастера:`n','wmza','1.1.2 Dragonprime Edition '),
('ru','masters','`^Master\'s speech when player loses:`n','`^Мастер скажет когда игрок проиграет:`n','wmza','1.1.2 Dragonprime Edition '),
('ru','masters','`^Master\'s speech when player wins:`n','`^Мастер скажет когда игрок выиграет:`n','wmza','1.1.2 Dragonprime Edition '),
('ru','masters','`^Master\'s weapon:`n','`^Оружие мастера:`n','wmza','1.1.2 Dragonprime Edition '),
('ru','masters','del','удал','wmza','1.1.2 Dragonprime Edition'),
('ru','masters','edit','измен','wmza','1.1.2 Dragonprime Edition');