9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','module-worldmapen','%s Modules','%s Модули','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','/?New Day','/?Новый день','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Chance for a special during travel','Шанс для специальностей вовремя путешествия','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Cities','Города','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Continue','Продолжить','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Current Location','Расположение','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Forest','Лес','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Game Settings','Настройки игры','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Journey','Путешествие','wmza','1.1.2 Dragonprime Edition '),
('ru','module-worldmapen','M?Return to the Mundane','Вернуться в игру','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Map','Карта','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Module Category - `^%s`0','Категория модуля - `^%s`0','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Module Configurations','Конфигурация модулей','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Module Manager','Менеджер модулей','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Random Event -Don\'t Edit','Случайное событие -Не Редактировать','wmza','1.1.2 Dragonprime Edition '),
('ru','module-worldmapen','Standard settings','Стандартные настройки','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Superuser','Администрация','','1.1.2 Dragonprime Edition'),
('ru','module-worldmapen','Turn on Superuser manual movement?','Включить руководство при движении суперпользователя','wmza','1.1.2 Dragonprime Edition '),
('ru','module-worldmapen','X?`bSuperuser Grotto`b','X?`bГротт администрации`b','','1.1.2 Dragonprime Edition');