9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','modulemanage',' ?%s - (%s modules)',' ?%s - (%s модулей)','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage',' ?Uninstalled - (%s modules)',' ?Неустановленных - (%s модулей)','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','(`$Invalid Module! Contact Author or check file!`0)','(`$Ошибка модуля! Свяжитесь с автором файла!`0)','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Activate','Включить','','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Administrative','Администрация','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Are you sure you wish to uninstall this module?  All user preferences and module settings will be lost.  If you wish to temporarily remove access to the module, you may simply deactivate it.','Вы уверены, что хотите удалить этот модуль? Все пользовательские настройки и настройки модуля будут потеряны. Если вы хотите временно удалить доступ к модулю, вы можете просто отключить его.','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Bank','Банк','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Category','Категория','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Cities','Города','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Darkhorse Game','Игра Темная Лошадь','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Deactivate','Отключить','','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Deleting module entry`n','Удаление модуля входа`n','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Deleting module hooks`n','Удаление модуля перехвата`n','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Deleting module object prefs`n','Удаление модуля привелегий обьекта`n','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Deleting module settings`n','Удаление модуля настроек`n','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Deleting module user prefs`n','Удаление модуля установок пользователя`n','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Filename','Название','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Forest','Лес','','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Gardens','Сады','','1.1.2 Dragonprime Edition'),
('ru','modulemanage','General','Основные','','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Inn','Трактир','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Install','Установка','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Installed On','Установленный','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Map','Карта','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Maps','Карты','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Module Author','Автор модуля','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Module Categories','Категории модулей','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Module Manager','Менеджер модулей','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Module Name','Название модуля','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Not installable','Не устанавливается','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Ops','Ops','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Races','Расы','','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Reinstall','Переустанов','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Running module uninstall script`n','Запуск модуля удаления скрипта`n','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Settings','Настройки','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Status','Статус','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Testing','Тестирование','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Translations','Переводы','','1.1.2 Dragonprime Edition'),
('ru','modulemanage','Uninstall','Удалить','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','Village','Город','','1.1.2 Dragonprime Edition'),
('ru','modulemanage','`#Eibwen`& flies in loops around your head. \"`3Not much to say here.  Fight monsters, gain gold, heal when you need to.  Most of all, have fun!`0\"`n`nHe flies off back toward the village.`n`nOver his shoulder, he calls out, \"`3Before I go, please read the FAQs... and the Message of the Day is something you should check each time you log in. Don\'t be afraid to explore, but don\'t be afraid to run away either! And just remember, dying is part of life!`0\"`n','`#Eibwen`& flies in loops around your head. \"`3Not much to say here.  Fight monsters, gain gold, heal when you need to.  Most of all, have fun!`0\"`n`nHe flies off back toward the village.`n`nOver his shoulder, he calls out, \"`3Before I go, please read the FAQs... and the Message of the Day is something you should check each time you log in. Don\'t be afraid to explore, but don\'t be afraid to run away either! And just remember, dying is part of life!`0\"`n','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','`$Inactive`0','`$Неактивно`0','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','`$No Settings`0','`$Нет настроек`0','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','`2Performing `^%s`2 on `%%s`0`n','`2Выполнено `^%s`2 в `%%s`0`n','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','`@Active`0','`@Активно`0','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','`^Module installed.  It is not yet active.`n','`^Модуль установлен.  Но не активен.`n','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','`bRequires:`b`n','`bТребует:`b`n','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','`bUninstalled Modules`b`n','`bНеустановленные модули`b`n','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','`i-- No Modules Installed--`i','`i-- Нет Установленных Модулей --`i','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','`n`b%s Modules`b`n','`n`b%s Модули`b`n','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','activate','включение','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','by %s','- %s','wmza','1.1.2 Dragonprime Edition '),
('ru','modulemanage','deactivate','деактив','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','install','установка','wmza','1.1.2 Dragonprime Edition'),
('ru','modulemanage','uninstall','удаление','wmza','1.1.2 Dragonprime Edition ');