9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','module-citygeneric1','Access','Доступ','','1.1.2 Dragonprime Edition'),
('ru','module-citygeneric1','Generic City 1 Settings','Настройки  города 1','wmza','1.1.2 Dragonprime Edition '),
('ru','module-citygeneric1','Hunter\'s Lodge','Дом охотников','','1.1.2 Dragonprime Edition'),
('ru','module-citygeneric1','Name for the village','Название города','wmza','1.1.2 Dragonprime Edition '),
('ru','module-citygeneric1','No','Нет','','1.1.2 Dragonprime Edition'),
('ru','module-citygeneric1','Restrict `^armor shop`0 from appearing in this village?','Включить `^Магазин брони`0 в этом городе?','wmza','1.1.2 Dragonprime Edition '),
('ru','module-citygeneric1','Restrict `^bank`0 from appearing in this village?','Включить `^Банк`0 в этом городе?','wmza','1.1.2 Dragonprime Edition '),
('ru','module-citygeneric1','Restrict `^clan entry`0 from appearing in this village?','Включить `^Вход в кланы`0 в этом городе?','wmza','1.1.2 Dragonprime Edition '),
('ru','module-citygeneric1','Restrict `^forest`0 from appearing in this village?','Включить `^лес`0 в этом городе?','wmza','1.1.2 Dragonprime Edition '),
('ru','module-citygeneric1','Restrict `^gardens`0 from appearing in this village?','Включить `^сады`0 в этом городе?','wmza','1.1.2 Dragonprime Edition '),
('ru','module-citygeneric1','Restrict `^gypsy`0 tent from appearing in this village?','Включить `^Гипси`0 в этом городе?','wmza','1.1.2 Dragonprime Edition '),
('ru','module-citygeneric1','Restrict `^lodge`0 from appearing in this village?','Включить `^договора охотников`0 в этом городе?','wmza','1.1.2 Dragonprime Edition'),
('ru','module-citygeneric1','Restrict `^pvp`0 in this village?','Включить `^ПвП`0 в этом городе?','wmza','1.1.2 Dragonprime Edition '),
('ru','module-citygeneric1','Restrict `^weapon shop`0 from appearing in this village?','Включить `^Магазин оружия`0 в этом городе?','wmza','1.1.2 Dragonprime Edition '),
('ru','module-citygeneric1','Travel','Путешествовать','','1.1.2 Dragonprime Edition'),
('ru','module-citygeneric1','all','все','wmza','1.1.2 Dragonprime Edition ');