9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','module-racehuman','%s, City of Men','%s, Город Людей','wmza','1.1.2 Dragonprime Edition'),
('ru','module-racehuman','Chance for Humans to die in the mine','Шанс умереть человеку в шахте','wmza','1.1.2 Dragonprime Edition '),
('ru','module-racehuman','How many extra forest fights for humans?','Сколько дополнительно боев в лесу для людей','wmza','1.1.2 Dragonprime Edition'),
('ru','module-racehuman','Human Race Settings','Настройки расы людей','wmza','1.1.2 Dragonprime Edition '),
('ru','module-racehuman','M?Bertold\'s Bestiary`0','M?Бестиарий Бертольда`0','wmza','1.1.2 Dragonprime Edition'),
('ru','module-racehuman','Name for the human village','Название деревни людей','wmza','1.1.2 Dragonprime Edition '),
('ru','module-racehuman','Village Gates','Городские ворота','','1.1.2 Dragonprime Edition'),
('ru','module-racehuman','`&As a human, your size and strength permit you the ability to effortlessly wield weapons, tiring much less quickly than other races.`n`^You gain %s extra forest %s each day!','`&Как человек, ваш размер и сила позволяют вам возможность легко виды оружия, гораздо менее утомительно быстрее, чем другие расы.`n`^Вы получаете %s леса %s каждый день!','wmza','1.1.2 Dragonprime Edition '),
('ru','module-racehuman','`&Human`0','`&Человек`0','wmza','1.1.2 Dragonprime Edition '),
('ru','module-racehuman','`0<a href=\'newday.php?setrace=Human\'>On the plains in the city of %s</a>, the city of `&men`0; always following your father and looking up to his every move, until he sought out the `@Green Dragon`0, never to be seen again.`n`n','`0<a href=\'newday.php?setrace=Human\'>Вы родились %s</a>на равнинах города Ромар, в городе `&людей`0; во всем следуя за своим отцом и подражая ему, до тех пор, пока тот не ушел на поиски `@Зеленого дракона`0, и больше уже никогда не вернулся.`n`n','wmza','1.1.2 Dragonprime Edition '),
('ru','module-racehuman','`n`&Because you are human, you gain `^%s extra`& forest fights for today!`n`0','`n`&За точ то вы человек, Вы получаете `^%s дополнительных`& поединка в лесу!`n`0','wmza','1.1.2 Dragonprime Edition '),
('ru','module-racehuman','`n`&Nearby some villagers talk:`n','`n`&Жители по соседству говорят:`n','wmza','1.1.2 Dragonprime Edition'),
('ru','module-racehuman','`n`7A smaller contraption next to it reads `&%s`7, `&%s %s %s`7.`n','`n`7Маленьких хитрец рядом с ним читает `&%s`7, `&%s %s %s`7.`n','wmza','1.1.2 Dragonprime Edition'),
('ru','module-racehuman','`n`7The great sundial at the heart of the city reads `&%s`7.`n','`n`7Большие солнечные часы в центре города показывают `&%s`7.`n','wmza','1.1.2 Dragonprime Edition'),
('ru','module-racehuman','an','1','wmza','1.1.2 Dragonprime Edition'),
('ru','module-racehuman','fight','поединок','wmza','1.1.2 Dragonprime Edition '),
('ru','module-racehuman','fights','поединка','wmza','1.1.2 Dragonprime Edition '),
('ru','module-racehuman','says','говорит','','1.1.2 Dragonprime Edition'),
('ru','module-racehuman','three','3','wmza','1.1.2 Dragonprime Edition'),
('ru','module-racehuman','two','2','wmza','1.1.2 Dragonprime Edition');