9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','module-modloc','%s','%s','','1.1.2 Dragonprime Edition'),
('ru','module-modloc','Current Location','Расположение','wmza','1.1.2 Dragonprime Edition '),
('ru','module-modloc','Currently showing all location settings.','С указанием всех параметров расположения.','wmza','1.1.2 Dragonprime Edition '),
('ru','module-modloc','Filter','Фильтр','wmza','1.1.2 Dragonprime Edition '),
('ru','module-modloc','Location Question','Вопрос локации','wmza','1.1.2 Dragonprime Edition '),
('ru','module-modloc','Mechanics','Механика','','1.1.2 Dragonprime Edition'),
('ru','module-modloc','Module Location List','Модуль списка локаций','wmza','1.1.2 Dragonprime Edition '),
('ru','module-modloc','Module Locations','Модуль локаций','wmza','1.1.2 Dragonprime Edition '),
('ru','module-modloc','Module Name','Название модуля','','1.1.2 Dragonprime Edition'),
('ru','module-modloc','Navigation','Навигация','','1.1.2 Dragonprime Edition'),
('ru','module-modloc','Settings','Настройки','','1.1.2 Dragonprime Edition'),
('ru','module-modloc','Settings Link','Настройка ссылки','wmza','1.1.2 Dragonprime Edition '),
('ru','module-modloc','Show All','Смотреть все','wmza','1.1.2 Dragonprime Edition '),
('ru','module-modloc','Show Errors','Смотреть ошибки','wmza','1.1.2 Dragonprime Edition '),
('ru','module-modloc','View Module Locations','Смотреть модули локаций','wmza','1.1.2 Dragonprime Edition '),
('ru','module-modloc','`@`c`iDue to the fact that some sites can become very cluttered, this tool allows you to see all modules with location settings, and to which location they are hooked. You can also view by city.`i`c`n`n','`@`c`iВ связи с тем, что некоторые сайты могут стать очень загроможденны, этот инструмент позволяет вам увидеть все модули настройки местоположения, и какое место они подключены. Вы можете также просмотреть по городу.`i`c`n`n','wmza','1.1.2 Dragonprime Edition '),
('ru','module-modloc','`n`^`bModule Location List:`b`0`n','`n`^`bМодуль списка локаций:`b`0`n','wmza','1.1.2 Dragonprime Edition ');