9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','module-tutor','\"`3The `^forest`3 is worth visiting, too. That\'s where you gain experience and gold!`0\"`n','\"`3В `^лес`3 стоит заходить почаще. Здесь вы получите опыт и золото!`0\"`n','wmza','1.1.2 Dragonprime Edition'),
('ru','module-tutor','%s','%s','wmza','1.1.2 Dragonprime Edition'),
('ru','module-tutor','%s`c`b`#%s`n%s`n%s`b`c','%s`c`b`#%s`n%s`n%s`b`c','wmza','1.1.2 Dragonprime Edition'),
('ru','module-tutor','%s`c`b`#%s`n%s`n%s`n%s`n`b`c','%s`c`b`#%s`n%s`n%s`n%s`n`b`c','wmza','1.1.2 Dragonprime Edition'),
('ru','module-tutor','*?`$Help Me, I\'m Lost!','*?`$ПОМОГИТЕ МНЕ!','wmza','1.1.2 Dragonprime Edition'),
('ru','module-tutor','Dark Arts','Темное исскуство','wmza','1.1.2 Dragonprime Edition'),
('ru','module-tutor','Dwarf','Гном','wmza','1.1.2 Dragonprime Edition '),
('ru','module-tutor','Elf','Эльф','wmza','1.1.2 Dragonprime Edition '),
('ru','module-tutor','Has the player seen the forest instructions','Игроку увидит инструкции в лесу?','wmza','1.1.2 Dragonprime Edition '),
('ru','module-tutor','Human','Человек','wmza','1.1.2 Dragonprime Edition '),
('ru','module-tutor','In-Game tutor User Preferences','Настройки наставника в игре','wmza','1.1.2 Dragonprime Edition '),
('ru','module-tutor','Mystical Powers','Мистические Силы','wmza','1.1.2 Dragonprime Edition '),
('ru','module-tutor','Thieving Skills','Воровские способности','wmza','1.1.2 Dragonprime Edition '),
('ru','module-tutor','Troll','Троль','wmza','1.1.2 Dragonprime Edition '),
('ru','module-tutor','Turn off the tutor help?','Выключить помощь наставника?','wmza','1.1.2 Dragonprime Edition ');