9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','module-outhouse','He politely turns his back to you and finishes cleaning the wash stand.`n','Он вежливо поворачивается к вам спиной и закрывает за вами дверь.`n','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','Hold it','Подождать','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','In typical caste style, there is a privileged outhouse, and an underprivileged outhouse.','Есть отдельный туалет в стиле замка, и есть большие кусты из репейника.','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','Leave','Выйти','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','O?The Outhouse','Пристройки','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','Private Toilet: (%s gold)','Отдельный туалет: (%s золота)','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','Public Toilet: (free)','В кустах: (бесплатно)','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','The Outhouses','Пристройки','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','The Outhouses are closed for repairs.`n','Пристройки закрыты на ремонт.`n','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','The Toilet Paper Gnome tells you if you need anything, just ask.`n','Гном говорит что если вам потребуеться туалетная бумага, просто попросите.`n','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','The choice is yours!`0`n`n','Какой ваш выбор!`0`n`n','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','This is the cleanest outhouse in the land!`n','Это самый чистый туалет в мире!`n','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','Toilets','Туалеты','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','Wash Stand','Умывальник','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','Wash your hands','Помыть руки','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','You will have to hold it till tomorrow!','Ремонт продлиться до завтра!','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','`2The nearby village has two outhouses, which it keeps way out here in the forest because of the warding effect of their smell on creatures.`n`n','`2Возле деревни стоят два туалета, любой путник или искатель приключения может посетить их и облегчиться.`n`n','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','`2Washing your hands is always a good thing.  You tidy up, straighten your %s in your reflection in the water, and head on your way.`0`n','`2Всегда полезно мыть руки. Вы смотритесь в зеркало, поправляете %s умываетесь, и расчесываете себе волосы.`0`n','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','`7You pay your %s gold to the Toilet Gnome for the privilege of using the paid outhouse.`n','`7Вы платите %s золота Гному у дверей в чтобы посетить туалет.`n','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','`7You receive `^%s`7 gold for being sanitary and clean!`0`n','`7Вы получаете `^%s`7 золотых за то-что хорошо выглядите!`0`n','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','`^The Wash Room Fairy blesses you!`n','`^Фея красоты благословляет вас!`n','wmza','1.1.2 Dragonprime Edition '),
('ru','module-outhouse','`n`n`7You return to the forest.`0','`n`n`7Вы возвращаетесь в лес.`0','wmza','1.1.2 Dragonprime Edition ');