9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','mounts','%s Modules','%s Модули','wmza','1.1.2 Dragonprime Edition'),
('ru','mounts','Activate','Включить','wmza','1.1.2 Dragonprime Edition'),
('ru','mounts','Add a mount','Добавить питомца','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Buff name:','Название баффа:','wmza','1.1.2 Dragonprime Edition'),
('ru','mounts','Category: %s','Категория: %s','wmza','1.1.2 Dragonprime Edition'),
('ru','mounts','Cost','Стоимость','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Deactivate','Отключить','','1.1.2 Dragonprime Edition'),
('ru','mounts','Del','Удалить','','1.1.2 Dragonprime Edition'),
('ru','mounts','Each round:','Каждый раунд:','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Edit','Изменить','','1.1.2 Dragonprime Edition'),
('ru','mounts','Effect:','Эффект:','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Everywhere','Везде','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Features','Особенности','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Give','Дать','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','If there are any owners of the mount when it is deleted, they will no longer have a mount, but they will get a FULL refund of the price of the mount at the time of deletion.','Если есть владельцы у питомца, когда он удаляется, они больше не будут иметь питомца, но они получат полный возврат цен за питомца во время удаления.','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Mount Availability:','Наличие питомца:','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Mount Buff:','Баффы питомца:','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Mount Category:','Категория питомца:','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Mount Cost (DKs):','Стоимость питомца (ДК):','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Mount Cost (Gems):','Стоимость питомца (Кристалы):','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Mount Cost (Gold):','Стоимость питомца (Золото):','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Mount Description:','Описание питомца:','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Mount Editor','Редактор питомцев','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Mount Editor Home','Редактор питомцев','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Mount Editor:`n','Редактор питомцев:`n','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Mount Feed Cost`n(Gold per level):','Стоимость корма питомцу`n(Золота за уровень):','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Mount Name:','Название питомца:','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Mount properties','Свойства питомцев','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Name','Название','wmza','1.1.2 Dragonprime Edition'),
('ru','mounts','New Day:','Новый день:','wmza','1.1.2 Dragonprime Edition'),
('ru','mounts','Ops','Ops','wmza','1.1.2 Dragonprime Edition'),
('ru','mounts','Owners','Владельцы','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Regen:','Регенерация:','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','Save','Сохранить','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','The Village of %s','В городе %s','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','There are %s user(s) who own this mount, are you sure you wish to delete it?','Есть %s игроков которые владеют этим питомцев, Вы уверены что хотите удалить его?','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','`%%s gems`0, `^%s gold`0','`%%s кристалы`0, `^%s золота`0','wmza','1.1.2 Dragonprime Edition'),
('ru','mounts','`&Pony Attack','`&Атака Пони','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','`&Атака Пони','`&Атака Пони','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','`5Ваш Пони борется рядом с вами!`0`n','`5Ваш Пони борется рядом с вами!`0`n','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','`^Mount saved!`0`n','`^Питомец сохраненн!`0`n','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','`bBuff Messages:`b`n','`bСообщение баффа:`b`n','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','`bMount Messages:`b','`bСообщения питомцев:`b','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','`nIf you wish to delete a mount, you have to deactivate it first.','`nЕсли вы хотите удалить питомца, вы должны сначала отключить его.','wmza','1.1.2 Dragonprime Edition '),
('ru','mounts','`n`bEffects:`b`n','`n`bЕффекты:`b`n','wmza','1.1.2 Dragonprime Edition');