9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','newday','??F.A.Q. (Frequently Asked Questions)','??F.A.Q. (Frequently Asked Questions)','wmza','1.1.2 Dragonprime Edition'),
('ru','newday','A little history about yourself','Немного истории о себе','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','Advancements made by spending dragon points are permanent!','Потраченные очки дракона невозможно изменить.','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','Attack + 1','Атака + 1','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','Continue','Продолжить','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','Defense + 1','Защита + 1','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','Dragon Points','Очки Дракона','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','Forest Fights + 1','Лесные Поединки + 1','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','High','Высокое','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','How do you wish to spend it?`n`n','Как вы хотите их распределить?`n`n','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','It is a new day!','Настал новый день!','wmza','1.1.2 Dragonprime Edition'),
('ru','newday','Low','Низкое','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','Max Hitpoints + 5','Макс. Жизни + 5','wmza','1.1.2 Dragonprime Edition'),
('ru','newday','Normal','Нормальное','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','One or more of your characters in Legend of the Green Dragon at %s is about to expire.  If you wish to keep this character, you should log on to him or her soon!','Один или несколько из ваших персонажей в Легенда о Зеленом Драконе %s подходит к концу. Если Вы хотите сохранить этот символ, вы должны войти в его или ее скоро!
','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','Resurrected','Воскресший','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','Very High','Очень высокое','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','Very Low','Очень низкое','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','What do you recall doing as a child?`n`n','Чем вы занимались в детстве?`n`n','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','Where do you recall growing up?`n`n','Что вы помните о детстве?`n`n','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','You earn one dragon point each time you slay the dragon.','вы зарабатываете одно очко дракона каждый раз при убийстве дракона.','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','You feel refreshed enough to take on the world!`n','Вы чувствуете себя достаточно бодро, чтобы войти в этот мир!`n','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','You open your eyes to discover that a new day has been bestowed upon you. It is day number `^%s.`0','Вы открываете глаза и понимаете, что Вам подарен ещё один день этой жизни. Это Ваш `^%s день.`0','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','`2As a result, you `^%s %s forest %s`2 for today!`n','`2В результате, Вы получаете `^%s %s лесных %s`2 поединков!`n','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','`2Hitpoints have been restored to `^%s`2.`n','`2Сегодня у вас есть `^%s поединков`2.`n','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','`2Today\'s interest rate: `^0% (Bankers in this village only give interest to those who work for it)`2.`n','`2Сегодня Банк начислил процент по вкладу в размере: `^0% (Банкиры не платят проценты если вы не работаете в лесу)`2.`n','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','`2Turns for today set to `^%s`2.`n','`2Сегодня у вас есть `^%s поединков`2.`n','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','`@You are resurrected!  This is resurrection number %s.`0`n','`@Вы воскресли! Это %s воскрешение.`0`n','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','`@You have `&1`@ unspent dragon point.','`@У вас есть `&1`@ неизрасходованные очки дракона.','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','`c`b`#It is a New Day!`0`b`c','`c`b`#Настал новый день!`0`b`c','wmza','1.1.2 Dragonprime Edition'),
('ru','newday','`n`&Because of %s`&, you %s%s %s`& forest %s for today!`n`0','`n`&За вашего %s`&, вы %s%s %s`& лесных %s на этот день!`n`0','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','`n`&You strap your %s to your pony\'s saddle bags, and head out for some adventure!`0`n','`n`&Вы привязываете свой %s к мешку вашего скауна, и отправляетесь на поиски приключений!`0`n','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','`n`&You strap your `%%s`& to your back and head out for some adventure.`0','`n`&Вы закидываете своё оружие `%%s`& за спину и отправляетесь на поиски приключений.`0','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','`n`2You are in `^%s`2 spirits today!`n','`n`2Настроение духа сегодня `^%s`2!`n','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','`n`nCurrently, the dragon points you have already spent are distributed in the following manner.','`n`nВ настоящее время, дракон очков вы уже потратили распределяются следующим образом.','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','fight','Поединки','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','fights','поединка','','1.1.2 Dragonprime Edition'),
('ru','newday','gain','получаете','wmza','1.1.2 Dragonprime Edition '),
('ru','newday','lose','-','wmza','1.1.2 Dragonprime Edition ');