9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','prefs','Account Preferences','Настройки аккаунта','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Allow profanity in received Ye Olde Poste messages?','Допускать брань (не фильтрованный базар) при получении новой почты ?','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Display Preferences','Дисплейные предпочтения','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Don\'t jump to comment areas after refreshing or posting a comment?','Перепрыгивать на чат после добавления или обновления комментария?','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Email Address','Email адресс','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','English','English','wmza','1.1.2 Dragonprime Edition'),
('ru','prefs','Game Behavior Preferences','Предпочтение поведения игры','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Hours to offset time displays (%s currently displays as %s)?','Часы, чтобы компенсировать показы времени ( настоящему времени показывает как %s)?','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','In-Game tutor User Preferences','Настройки наставника в игре','','1.1.2 Dragonprime Edition'),
('ru','prefs','Language','Язык','wmza','1.1.2 Dragonprime Edition'),
('ru','prefs','None','Пусто','','1.1.2 Dragonprime Edition'),
('ru','prefs','Password','Пароль','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Preferences','Настройки игрока','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Real Time [12/25 1:27pm]','Реальное время [12/25 1:27pm]','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Relative Time (1h35m)','Относительное время (1h35m)','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Return to the news','Вернуться к новостям','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Retype','Повторить пароль','wmza','1.1.2 Dragonprime Edition'),
('ru','prefs','Send email for system generated messages?','Оповещать по E-mail при получении новых сообщений ?','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Send email when you get new Ye Olde Mail?','Оповещать по E-mail о получении новой почты ?','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Settings Saved','Настройки Сохранены','wmza','1.1.2 Dragonprime Edition'),
('ru','prefs','Short Character Biography (255 chars max)','Краткая Биография (максимум 255 знаков)','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Show config sections in tabs','Показать конфиг секции в таб.','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Show timestamps in commentary?','Показывать отметки времени в комментариях?','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Skin','Вид отображения (Оболочка)','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Timestamp format (currently displaying time as %s whereas default format is \"[m/d h:ia]\")','Формат отметки времени (к настоящему времени отображающее время как [08/30 01:42pm] поскольку по умолчанию формат \"[m/d h:ia]\")','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Turn off the tutor help?','Выключить помощь наставника?','','1.1.2 Dragonprime Edition'),
('ru','prefs','Your password is too short.  It must be at least 4 characters long.','Ваш пароль слишком маленький. Минимальная длина 4 символа.','wmza','1.1.2 Dragonprime Edition '),
('ru','prefs','Русский','Русский','','1.1.2 Dragonprime Edition');