9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','superuser','Actions','Действия','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Armor Editor','Редактор брони','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','B?Player Bios','Основы игрока','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','C?Recent Commentary','Последние комментария','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Companion Editor','Редактор спутников','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Donator Page','Страница доната','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','E?Creature Editor','Редактор существ','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Editors','Редакторы','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Game Settings','Настройки игры','wmza','1.1.2 Dragonprime Edition'),
('ru','superuser','Gamelog Viewer','Просмотр лога игры','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Inside you are greeted by the sight of numerous scantily clad buxom women who wave palm fronds at you and offer to feed you grapes as you lounge on Greco-Roman couches draped with silk.`n`n','Здесь вы можете управлять игрой.`n`n','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Manage Modules','Менеджер модулей','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Master Editor','Редактор мастеров','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Mechanics','Механика','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Module Configurations','Конфигурация модулей','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Mount Editor','Редактор питомцев','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Nasty Word Editor','Редактор антимата','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Payment Log','Логи оплаты','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Petition Viewer','Просмотр жалоб','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Q?Run Raw SQL','Выполнить SQL запрос','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Referring URLs','URL ссылки','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Stats','Статистика','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Superuser Grotto','Админка','wmza','1.1.2 Dragonprime Edition'),
('ru','superuser','Taunt Editor','Редактор насмешек','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','Title Editor','Редактор Титулов','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','U?Untranslated Texts','Непереведенный текст','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','User Editor','Редактор игрока','','1.1.2 Dragonprime Edition'),
('ru','superuser','Weapon Editor','Редактор оружия','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','`^You duck into a secret cave that few know about. ','`^Вы вошли в секретную пещеру о которой многие не знают. ','wmza','1.1.2 Dragonprime Edition '),
('ru','superuser','says','говорит','wmza','1.1.2 Dragonprime Edition ');