9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','train','A small crowd of onlookers has gathered, and you briefly notice the smiles on their faces, but you feel confident. ','Небольшая толпа зевак собралась, и вы вкратце заметить улыбки на их лицах, но вы чувствуете себя уверенно.','wmza','1.1.2 Dragonprime Edition '),
('ru','train','Bluspring\'s Warrior Training','Тренировка воинов','wmza','1.1.2 Dragonprime Edition '),
('ru','train','M?Challenge Master','Сразиться с Мастером','wmza','1.1.2 Dragonprime Edition '),
('ru','train','Meekly you retrieve your %s, and slink out of the training grounds to the sound of boisterous guffaws.','Вы поднимаете свой %s, и убегаете из полигона под звуки хохота.','wmza','1.1.2 Dragonprime Edition '),
('ru','train','Question Master','Спросить Мастера','wmza','1.1.2 Dragonprime Edition '),
('ru','train','Superuser Gain level','Усилить уровень суперпольз','wmza','1.1.2 Dragonprime Edition '),
('ru','train','The sound of conflict surrounds you.  The clang of weapons in grisly battle inspires your warrior heart. ','Вас окружают звуки поединков. Звон оружия в ужасной битве вдохновляет ваше сердце воина.','wmza','1.1.2 Dragonprime Edition '),
('ru','train','Well done %s`&, I should have guessed you\'d grown some.','Вы молодец %s`&, Я должен был догадаться что выросли.','wmza','1.1.2 Dragonprime Edition '),
('ru','train','Well done %s`&, you really know how to use your %s.','Очень хорошо %s`&, Вы знаете как использовать ваш %s.','wmza','1.1.2 Dragonprime Edition '),
('ru','train','With a flurry of blows you dispatch your master.`n','Вы посылаете шквал ударов своему Мастеру.`n','wmza','1.1.2 Dragonprime Edition '),
('ru','train','You bow before `^%s`0, and execute a perfect spin-attack, only to realize that you are holding NOTHING!','Вы делаете поклон `^%s`0, и наносите сильную атаку в спину, НО вы замечаете что у вас в руках НИЧЕГО НЕТ!','wmza','1.1.2 Dragonprime Edition '),
('ru','train','You gain a defense point!`n','Вы увеличили защиту!`n','wmza','1.1.2 Dragonprime Edition '),
('ru','train','You gain an attack point!`n','Вы увеличили атаку!`n','wmza','1.1.2 Dragonprime Edition'),
('ru','train','You have a new master.`n','У Вас появился новый Мастер.`n','wmza','1.1.2 Dragonprime Edition '),
('ru','train','You ready your %s and %s and approach `^%s`0.`n`n','Вы готовите свой %s и %s перед нападением на `^%s`0.`n`n','wmza','1.1.2 Dragonprime Edition '),
('ru','train','Your maximum hitpoints are now `^%s`#!`n','Ваша максимальная жизнь стала `^%s`#!`n','wmza','1.1.2 Dragonprime Edition '),
('ru','train','`#You advance to level `^%s`#!`n','`#Вы получили уровень `^%s`#!`n','wmza','1.1.2 Dragonprime Edition '),
('ru','train','`&You now feel free to make use of your buffs again!`0`n','`&Теперь у вас снова появились бафы!`0`n','wmza','1.1.2 Dragonprime Edition '),
('ru','train','`&Your pride prevents you from using extra abilities during the fight!`0`n','`&Ваша гордасть не позволяет вам использовать дополнительные возможности во время боя!`0`n','wmza','1.1.2 Dragonprime Edition '),
('ru','train','`^%s`0 stands before you holding your weapon.','`^%s`0 стоит перед вами держа в своих руках грозное оружие.','wmza','1.1.2 Dragonprime Edition '),
('ru','train','`b`$You have defeated %s!`0`b`n','`b`$Ты победил %s!`0`b`n','wmza','1.1.2 Dragonprime Edition '),
('ru','train','`b`cBluspring\'s Warrior Training`c`b','`b`cТренировка Воинов`c`b','wmza','1.1.2 Dragonprime Edition '),
('ru','train','`n`n`^%s stands ready to evaluate you.`0','`n`n`^%s готова оценить вас.`0','wmza','1.1.2 Dragonprime Edition ');