9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','untranslated','Congratulations!!!','Поздравляю!!','wmza','1.1.2 Dragonprime Edition '),
('ru','untranslated','Known Namespaces:','Известно расположение:','wmza','1.1.2 Dragonprime Edition '),
('ru','untranslated','N?Translate by Namespace','Переводить по Расположениям','wmza','1.1.2 Dragonprime Edition '),
('ru','untranslated','Namespace: %s','Расположение: %s','','1.1.2 Dragonprime Edition'),
('ru','untranslated','No rows found','Не найдено строк','wmza','1.1.2 Dragonprime Edition '),
('ru','untranslated','Ops','Ops','wmza','1.1.2 Dragonprime Edition'),
('ru','untranslated','Please change your language to translate these texts.','Пожалуйста, измените ваш язык, чтобы переводить эти тексты.','wmza','1.1.2 Dragonprime Edition '),
('ru','untranslated','R?Restart Translator','Рестарт переводчика','wmza','1.1.2 Dragonprime Edition '),
('ru','untranslated','Save Translation','Сохранить перевод','','1.1.2 Dragonprime Edition'),
('ru','untranslated','Show','Показать','wmza','1.1.2 Dragonprime Edition '),
('ru','untranslated','Skip Translation','Пропустить перевод','','1.1.2 Dragonprime Edition'),
('ru','untranslated','Target Language: %s','Язык перевода: %s','','1.1.2 Dragonprime Edition'),
('ru','untranslated','Text','Текст','wmza','1.1.2 Dragonprime Edition '),
('ru','untranslated','There are `&%s`^ untranslated texts in the database, but none for your selected language.','Tcnm `&%s`^ непереведенного текста в базе, но не для вашего выбранного языка.','wmza','1.1.2 Dragonprime Edition '),
('ru','untranslated','There are no untranslated texts in the database!','В базе нету непереведенных текстов!','wmza','1.1.2 Dragonprime Edition '),
('ru','untranslated','Untranslated Texts','Непереведенные тексты','wmza','1.1.2 Dragonprime Edition '),
('ru','untranslated','Updated','Обновлено','wmza','1.1.2 Dragonprime Edition'),
('ru','untranslated','`^`cThere are `&%s`^ untranslated texts in the database.`c`n`n','`^`cВ базе есть `&%s`^ непереведенного текста.`c`n`n','','1.1.2 Dragonprime Edition');