9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','user','%s Modules','%s Модули','','1.1.2 Dragonprime Edition'),
('ru','user','%s has changed to %s.`n','%s было изменено на %s.`n','wmza','1.1.2 Dragonprime Edition '),
('ru','user','1 week','1 недели','wmza','1.1.2 Dragonprime Edition '),
('ru','user','2 months','2 месяца','wmza','1.1.2 Dragonprime Edition '),
('ru','user','2 weeks','2 недели','wmza','1.1.2 Dragonprime Edition '),
('ru','user','3 weeks','3 недели','wmza','1.1.2 Dragonprime Edition '),
('ru','user','4 weeks','4 недели','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Account Locked','Игрок заблокирован','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Account info','Информация игрока','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Add a ban','Отправить в Бан','wmza','1.1.2 Dragonprime Edition'),
('ru','user','Add donation points','Дать очки пожертвований','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Are you sure you wish to delete this user?','Вы уверены что хотите удалить этого игрока?','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Are you sure you wish to issue a permanent ban?','Вы уверенны что хотите выдать постоянный БАН?','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Average page gen time is %s seconds`n','Среднее время создание страницы %s секунд`n','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Ban','Бан','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Bans','Баны','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Battle Info','Информация боев','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Bio','Биография','','1.1.2 Dragonprime Edition'),
('ru','user','Buff List','Список баффов','wmza','1.1.2 Dragonprime Edition'),
('ru','user','Changed player name to %s`0`n','Изменен игрок под именем %s`0`n','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Clan','Клан','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Clan Info','Информация клана','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Clan Join Date','Вступил в клан','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Clan Rank','Ранг в клане','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Days (0 for permanent)`n','Дней (0 для постоянного)`n','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Del','Удалить','','1.1.2 Dragonprime Edition'),
('ru','user','Display debug log','Смотреть дебаг лог','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Don\'t mess with me.','Не связывайся со мной.','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Edit','Изменить','','1.1.2 Dragonprime Edition'),
('ru','user','Edit user','Редактировать игрока','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Email','Email','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Email Address','Email адресс','','1.1.2 Dragonprime Edition'),
('ru','user','Female','Женский','','1.1.2 Dragonprime Edition'),
('ru','user','For an IP ban, enter the beginning part of the IP you wish to ban if you wish to ban a range, or simply a full IP to ban a single IP`n`n','Для IP запрет, введите начальной части IP вы хотите запретить, если вы хотите запретить диапазона, или просто полный IP запретить одного IP`n`n','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Forever','Никогда','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Gems','Кристаллы','','1.1.2 Dragonprime Edition'),
('ru','user','Grant New Day','Дать Новый День','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Has the referring player been awarded points','Сколько баллов получил игрок за реффералов','wmza','1.1.2 Dragonprime Edition '),
('ru','user','High','Высокое','','1.1.2 Dragonprime Edition'),
('ru','user','Hits','Входов','wmza','1.1.2 Dragonprime Edition '),
('ru','user','ID of player who referred this player','ID рефферала игрока который пригласил','wmza','1.1.2 Dragonprime Edition '),
('ru','user','ID: ','ID: ','wmza','1.1.2 Dragonprime Edition '),
('ru','user','IP: ','IP: ','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Last ID','Последний ID','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Last IP','Последний IP','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Last On','Последний вход','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Last On (local time)','Последний вход (локальное время)','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Level','Уровень','wmza','1.1.2 Dragonprime Edition'),
('ru','user','List/Remove bans','Список/Удаление банов','wmza','1.1.2 Dragonprime Edition'),
('ru','user','Log','Лог','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Login','Логин','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Low','Низкое','','1.1.2 Dragonprime Edition'),
('ru','user','Male','Мужской','','1.1.2 Dragonprime Edition'),
('ru','user','Mark Email As Valid','Подтвердить Email','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Name','Имя','wmza','1.1.2 Dragonprime Edition'),
('ru','user','New Password','Новый пароль','wmza','1.1.2 Dragonprime Edition '),
('ru','user','None','Пусто','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Normal','Нормальное','','1.1.2 Dragonprime Edition'),
('ru','user','Operations','Операции','','1.1.2 Dragonprime Edition'),
('ru','user','Ops','Ops','','1.1.2 Dragonprime Edition'),
('ru','user','Override Bans for this account','Запретить банить этого игрока','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Post ban','Поставить БАН','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Preferences','Настройки игрока','','1.1.2 Dragonprime Edition'),
('ru','user','Race','Раса','','1.1.2 Dragonprime Edition'),
('ru','user','Reason for the ban: ','Причина запрета: ','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Resurrected','Воскресший','','1.1.2 Dragonprime Edition'),
('ru','user','Save','Сохранить','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Search','Поиск','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Search by any field below: ','Поиск по любому полю: ','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Set up a new ban by IP or by ID (recommended IP, though if you have several different users behind a NAT, you can try ID which is easily defeated)`n','Настройка нового бана IP или ID (рекомендуется IP, хотя, если у вас есть несколько различных пользователей, находящихся за NAT, вы можете попробовать ID, который легко обойти)`n','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Set up ban','Настройка банов','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Setting %s to %s`n','Настройка %s в %s`n','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Sex','Пол','','1.1.2 Dragonprime Edition'),
('ru','user','Specialty','Специальность','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Stats','Статистика','','1.1.2 Dragonprime Edition'),
('ru','user','Total hits: %s`n','Всего показов: %s`n','wmza','1.1.2 Dragonprime Edition'),
('ru','user','Undecided','Нерешенный','wmza','1.1.2 Dragonprime Edition '),
('ru','user','User Editor','Редактор игрока','wmza','1.1.2 Dragonprime Edition '),
('ru','user','User id','Id игрока','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Very High','Очень высокое','','1.1.2 Dragonprime Edition'),
('ru','user','Very Low','Очень низкое','','1.1.2 Dragonprime Edition'),
('ru','user','View last page hit','Смотреть последн страницу','wmza','1.1.2 Dragonprime Edition '),
('ru','user','View user bio','Смотреть био игрока','wmza','1.1.2 Dragonprime Edition '),
('ru','user','Will Expire Within','Истекает в течении','wmza','1.1.2 Dragonprime Edition '),
('ru','user','`#Online`0','`#Онлайн`0','wmza','1.1.2 Dragonprime Edition '),
('ru','user','`$No results found`0','`$Результатов не найдено`0','wmza','1.1.2 Dragonprime Edition'),
('ru','user','`$This user is probably logged in at the moment!`0','`$Этот игрок находится в игре!`0','wmza','1.1.2 Dragonprime Edition '),
('ru','user','`$Warning:`0','`$Внимание:`0','wmza','1.1.2 Dragonprime Edition '),
('ru','user','`^Preferences for module %s saved.`n','`^Настройки для модуля %s сохранены.`n','wmza','1.1.2 Dragonprime Edition '),
('ru','user','`bShowing bans that will expire within 2 weeks.`b`n`n','`bПоказаны запреты которые истекают в течении 2 недель.`b`n`n','wmza','1.1.2 Dragonprime Edition '),
('ru','user','`nDuration: ','`nПродолжительность: ','wmza','1.1.2 Dragonprime Edition '),
('ru','user','`n`nLast Page Viewed:`n','`n`nПоследняя просмотренная страница:`n','wmza','1.1.2 Dragonprime Edition ');