9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','village','%s Square','%s Площадь','wmza','1.1.2 Dragonprime Edition'),
('ru','village','??F.A.Q. (newbies start here)','Помощь (старт для новичков)','wmza','1.1.2 Dragonprime Edition '),
('ru','village','A?Pegasus Armor','Броня от Пегаса','wmza','1.1.2 Dragonprime Edition'),
('ru','village','B?Ye Olde Bank','Старый банк','wmza','1.1.2 Dragonprime Edition'),
('ru','village','Blades Boulevard','Бульвар Лейзвий','wmza','1.1.2 Dragonprime Edition'),
('ru','village','C?Clan Halls','Клан Холл','wmza','1.1.2 Dragonprime Edition '),
('ru','village','City Gates','Городские Ворота','wmza','1.1.2 Dragonprime Edition '),
('ru','village','Edit','Изменить','wmza','1.1.2 Dragonprime Edition '),
('ru','village','F?Forest','Лес','wmza','1.1.2 Dragonprime Edition '),
('ru','village','G?The Gardens','Городские сады','wmza','1.1.2 Dragonprime Edition '),
('ru','village','I?The Boar\'s Head Inn`0','I?Гостиница Голова кабана`0','wmza','1.1.2 Dragonprime Edition'),
('ru','village','Info','Информация','wmza','1.1.2 Dragonprime Edition '),
('ru','village','J?JCP\'s Hunter Lodge','Логово охотников','wmza','1.1.2 Dragonprime Edition '),
('ru','village','L?List Warriors','Список воинов','wmza','1.1.2 Dragonprime Edition '),
('ru','village','M?Merick\'s Stables`0','Конюшня Мерика`0','wmza','1.1.2 Dragonprime Edition'),
('ru','village','Market Street','Торговая улица','wmza','1.1.2 Dragonprime Edition'),
('ru','village','Mercenary Camp','Лагерь Наемников','wmza','1.1.2 Dragonprime Edition'),
('ru','village','N?Daily News','Новости','wmza','1.1.2 Dragonprime Edition '),
('ru','village','Other','Другое','','1.1.2 Dragonprime Edition'),
('ru','village','P?Preferences','Настройки','wmza','1.1.2 Dragonprime Edition '),
('ru','village','Q?`%Quit`0 to the fields','Покинуть игру','wmza','1.1.2 Dragonprime Edition '),
('ru','village','S?Slay Other Players','Убить спящего','wmza','1.1.2 Dragonprime Edition '),
('ru','village','Tavern Street','Улица закусочых','wmza','1.1.2 Dragonprime Edition'),
('ru','village','W?MightyE\'s Weaponry','Оружие от Метью','wmza','1.1.2 Dragonprime Edition '),
('ru','village','Z?Ze Gypsy Tent','Циганский шатер','wmza','1.1.2 Dragonprime Edition'),
('ru','village','`5\"`6This both sucks and blows!`5\" wails %s.','`5\"`6This both sucks and blows!`5\" wails %s.','wmza','1.1.2 Dragonprime Edition'),
('ru','village','`n`3Module `#%s`3 is not active, but was attempted to be injected.`n','`n`3Модуль `#%s`3 не активен, но этот модуль установлен.`n','wmza','1.1.2 Dragonprime Edition'),
('ru','village','says','сказать','wmza','1.1.2 Dragonprime Edition '),
('ru','village','u?Bluspring\'s Warrior Training','Тренер воинов','wmza','1.1.2 Dragonprime Edition ');