9-15-2013 Verified Uploader:wmza Time:19:1:48
('ru','weapon','Add a weapon','Добавить оружие','wmza','1.1.2 Dragonprime Edition '),
('ru','weapon','Are you sure you wish to delete this weapon?','Вы уверены что хотите удалить это оружие?','wmza','1.1.2 Dragonprime Edition '),
('ru','weapon','Cost','Стоимость','wmza','1.1.2 Dragonprime Edition'),
('ru','weapon','Damage','Урон','wmza','1.1.2 Dragonprime Edition '),
('ru','weapon','Del','Удалить','wmza','1.1.2 Dragonprime Edition'),
('ru','weapon','Edit','Изменить','wmza','1.1.2 Dragonprime Edition'),
('ru','weapon','Editor','Редактор','wmza','1.1.2 Dragonprime Edition '),
('ru','weapon','Level','Уровень','wmza','1.1.2 Dragonprime Edition'),
('ru','weapon','Name','Название','wmza','1.1.2 Dragonprime Edition '),
('ru','weapon','Ops','Ops','','1.1.2 Dragonprime Edition'),
('ru','weapon','Weapon Editor','Редактор оружия','','1.1.2 Dragonprime Edition'),
('ru','weapon','Weapon Editor Home','Главная редактор оружия','wmza','1.1.2 Dragonprime Edition '),
('ru','weapon','Weapons for %s DKs','Оружие за %s ДК','wmza','1.1.2 Dragonprime Edition '),
('ru','weapon','Weapons for 1 DK','Оружие за 1 ДК','wmza','1.1.2 Dragonprime Edition '),
('ru','weapon','`&Weapons for %s Dragon Kills`0','`&Оружие за %s ДК`0','wmza','1.1.2 Dragonprime Edition ');